export enum UserRole {
  /** Cuenta registrada; el rol operativo se define tras el onboarding. */
  USER = 'USER',
  STUDENT = 'STUDENT',
  STUDENT_DELEGATE = 'STUDENT_DELEGATE',
  PROFESSOR = 'PROFESSOR',
  MODERATOR = 'MODERATOR',
  MANAGER = 'MANAGER',
  ADMIN = 'ADMIN',
}

/** Funciones en la universidad (una cuenta puede marcar varias). */
export enum StaffFunction {
  ESTUDIANTE = 'ESTUDIANTE',
  PROFESOR = 'PROFESOR',
  PDI_INVESTIGACION = 'PDI_INVESTIGACION',
  SECRETARIA_ADMINISTRACION = 'SECRETARIA_ADMINISTRACION',
  BIBLIOTECA = 'BIBLIOTECA',
  RECTORADO = 'RECTORADO',
  SEGURIDAD = 'SEGURIDAD',
  OTRO_PERSONAL = 'OTRO_PERSONAL',
}

export enum UserGender {
  MALE = 'Masculino',
  FEMALE = 'Femenino',
  OTHER = 'Otro',
  NOT_SPECIFIED = 'Prefiero no decirlo',
}

export enum UserCampus {
  AYNADAMAR = 'AYNADAMAR',
  CARTUJA = 'CARTUJA',
  FUENTENUEVA = 'FUENTENUEVA',
  PTS = 'PTS',
  CENTRO = 'CENTRO',
  CEUTA = 'CEUTA',
  MELILLA = 'MELILLA',
}

export enum UserFaculty {
  ETSIIT = 'Esc. Tec. Sup. Ing. Informática y Telecom.',
  ETSA = 'Esc. Tec. Sup. de Arquitectura',
  ETSIE = 'Esc. Tec. Sup. Ing. de Edificación',
  ETSICCP = 'Esc. Tec. Sup. Ing. de Caminos, Canales y Puertos',

  F_BA = 'Fac. de Bellas Artes',
  F_C = 'Fac. de Ciencias',
  F_CEE = 'Fac. de CC. Económicas y Empresariales',
  F_CPS = 'Fac. de CC. Políticas y Sociología',
  F_CSJ = 'Fac. de CC. Sociales y Jurídicas',
  F_CE = 'Fac. de CC. de la Educación',
  F_CED = 'Fac. de CC. de la Educación y del Deporte',
  F_CS = 'Fac. de CC. de la Salud',
  F_CD = 'Fac. de CC. del Deporte',
  F_CYD = 'Fac. de Comunicación y Documentación',
  F_D = 'Fac. de Derecho',
  F_EET = 'Fac. de Educación, Economía y Tecnología',
  F_F = 'Fac. de Farmacia',
  F_FL = 'Fac. de Filosofía y Letras',
  F_M = 'Fac. de Medicina',
  F_O = 'Fac. de Odontología',
  F_P = 'Fac. de Psicología',
  F_RLRH = 'Fac. de Relaciones Laborales y RR. HH.',
  F_TS = 'Fac. de Trabajo Social',
  F_TI = 'Fac. de Traducción e Interpretación',
}

export enum UserDegree {
  ADE = 'Grado en ADE',
  ADE_DERECHO = 'Doble Grado en ADE y Derecho',
  ANTROPOLOGIA = 'Grado en Antropología Social y Cultural',
  CC_POLITICAS = 'Grado en CC. Políticas y de la Administración',
  CC_POL_DERECHO = 'Doble Grado en CC. Políticas y Derecho',
  CC_POL_SOCIOLOGIA = 'Doble Grado en CC. Políticas y Sociología',
  CC_POL_PERIODISMO = 'Doble Grado en CC. Políticas y Periodismo',
  CRIMINOLOGIA = 'Grado en Criminología',
  DERECHO = 'Grado en Derecho',
  ECONOMIA = 'Grado en Economía',
  ECONOMIA_BIL = 'Grado en Economía (Bilingüe)',
  ED_INFANTIL = 'Grado en Educación Infantil',
  ED_PRIMARIA = 'Grado en Educación Primaria',
  ED_PRIMARIA_BIL = 'Grado en Educación Primaria (Bilingüe)',
  ED_SOCIAL = 'Grado en Educación Social',
  FICO = 'Grado en Finanzas y Contabilidad',
  GEOGRAFIA = 'Grado en Geografía y Gestión del Territorio',
  MARKETING = 'Grado en Marketing e Investigación de Mercados',
  PEDAGOGIA = 'Grado en Pedagogía',
  RLRH = 'Grado en Relaciones Laborales y RR. HH.',
  SOCIOLOGIA = 'Grado en Sociología',
  TRABAJO_SOCIAL = 'Grado en Trabajo Social',
  TURISMO = 'Grado en Turismo',

  BIOLOGIA = 'Grado en Biología',
  BIOQUIMICA = 'Grado en Bioquímica',
  BIOTECNOLOGIA = 'Grado en Biotecnología',
  CYTA = 'Grado en Ciencia y Tecnología de los Alimentos',
  CCAA = 'Grado en Ciencias Ambientales',
  CAFYD = 'Grado en CC. de la Actividad Física y del Deporte',
  ENFERMERIA = 'Grado en Enfermería',
  ESTADISTICA = 'Grado en Estadística',
  FARMACIA = 'Grado en Farmacia',
  FISICA = 'Grado en Física',
  FISIOTERAPIA = 'Grado en Fisioterapia',
  GEOLOGIA = 'Grado en Geología',
  LOGOPEDIA = 'Grado en Logopedia',
  MATEMATICAS = 'Grado en Matemáticas',
  MEDICINA = 'Grado en Medicina',
  NUTRICION = 'Grado en Nutrición Humana y Dietética',
  ODONTOLOGIA = 'Grado en Odontología',
  OPTICA = 'Grado en Óptica y Optometría',
  PSICOLOGIA = 'Grado en Psicología',
  QUIMICA = 'Grado en Química',
  TERAPIA_OCUPACIONAL = 'Grado en Terapia Ocupacional',

  ARQUITECTURA = 'Grado en Estudios de Arquitectura',
  EDIFICACION = 'Grado en Edificación',
  EDIF_ADE = 'Doble Grado en Edificación y ADE',
  ING_CIVIL = 'Grado en Ingeniería Civil',
  ING_CIVIL_ADE = 'Doble Grado en Ing. Civil y ADE',
  TELECO = 'Grado en Ingeniería de Tecnologías de Telecomunicación',
  ELECTRONICA = 'Grado en Ingeniería Electrónica Industrial',
  INFORMATICA = 'Grado en Ingeniería Informática',
  INF_ADE = 'Doble Grado en Ing. Informática y ADE',
  INF_MAT = 'Doble Grado en Ing. Informática y Matemáticas',
  ING_QUIMICA = 'Grado en Ingeniería Química',

  ARQUEOLOGIA = 'Grado en Arqueología',
  BELLAS_ARTES = 'Grado en Bellas Artes',
  COM_AUDIOVISUAL = 'Grado en Comunicación Audiovisual',
  CONSERVACION = 'Grado en Conservación y Restauración de Bienes Culturales',
  EST_ARABES = 'Grado en Estudios Árabes e Islámicos',
  EST_FRANCESES = 'Grado en Estudios Franceses',
  EST_INGLESES = 'Grado en Estudios Ingleses',
  FIL_CLASICA = 'Grado en Filología Clásica',
  FIL_HISPANICA = 'Grado en Filología Hispánica',
  FILOSOFIA = 'Grado en Filosofía',
  HISTORIA = 'Grado en Historia',
  HISTORIA_ARTE = 'Grado en Historia del Arte',
  HISTORIA_MUSICA = 'Grado en Historia y CC. de la Música',
  INF_DOC = 'Grado en Información y Documentación',
  LENGUAS_MODERNAS = 'Grado en Lenguas Modernas y sus Literaturas',
  LIT_COMPARADAS = 'Grado en Literaturas Comparadas',
  TRADUCCION_ALEMAN = 'Grado en Traducción e Interpretación (Alemán)',
  TRADUCCION_ARABE = 'Grado en Traducción e Interpretación (Árabe)',
  TRADUCCION_FRANCES = 'Grado en Traducción e Interpretación (Francés)',
  TRADUCCION_INGLES = 'Grado en Traducción e Interpretación (Inglés)',

  CAFYD_PRIMARIA = 'Doble Grado en CC. de la Actividad Física y Primaria',
  ED_PRIM_FRANCES = 'Doble Grado en Primaria y Estudios Franceses',
  ED_PRIM_INGLES = 'Doble Grado en Primaria y Estudios Ingleses',
  EST_ING_HISPANICAS = 'Doble Grado en Estudios Ingleses y Filología Hispánica',
  FARM_NUTRICION = 'Doble Grado en Farmacia y Nutrición Humana y Dietética',
  FISICA_MAT = 'Doble Grado en Física y Matemáticas',
  NUT_CYTA = 'Doble Grado en Nutrición Humana y Dietética y CYTA',
  TRAD_ALE_TURISMO = 'Doble Grado en Traducción (Alemán) y Turismo',
  TRAD_FRA_TURISMO = 'Doble Grado en Traducción (Francés) y Turismo',
  TRAD_ING_TURISMO = 'Doble Grado en Traducción (Inglés) y Turismo',
}
